# Generated by Django 3.0.2 on 2020-02-01 17:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=150)),
                ('slug', models.SlugField(max_length=200, unique_for_date=True)),
                ('body', models.TextField(db_index=True, max_length=5000)),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('time_published', models.DateTimeField(default=django.utils.timezone.now)),
                ('time_update', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], max_length=10)),
            ],
            options={
                'ordering': ['-time_published'],
            },
        ),
    ]
