# Generated by Django 3.0.2 on 2020-02-01 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mynews', '0004_auto_20200201_2355'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-time_publish']},
        ),
        migrations.RenameField(
            model_name='news',
            old_name='time_published',
            new_name='time_publish',
        ),
        migrations.AlterField(
            model_name='news',
            name='slug',
            field=models.SlugField(max_length=200, unique_for_date='time_publish'),
        ),
    ]
